### PR TITLE
Update vault dependency

### PR DESCRIPTION
**Pull request by indyfree**
Towards https://github.com/giantswarm/giantswarm/issues/3621.

See also https://github.com/giantswarm/vaultrole/pull/14, https://github.com/giantswarm/vaultcrt/pull/6, https://github.com/giantswarm/vaultpki/pull/4, https://github.com/giantswarm/vaulthealthz/pull/8.

Update vault to `0.10.3` to align with our infrastructure.

Also took the chance to move to `dep` and update all dependencies.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Here you need to check if the certificate generation still works as expected. There is https://github.com/giantswarm/giantswarm/issues/2070 and this is a little rabbit hole. There is also lots of different and old versions of `certctl` used in https://github.com/giantswarm/hive. So this has all to be sorted out and fixed. Please also check back with @giantswarm/sre.

**Comment by indyfree** [comment]
Oh oh, ok thanks for the heads up. :astonished:

**Comment by xh3b4sd** [comment]
You are my very favourite when you tackle this issue. Let me know when I can help somehow.

**Comment by indyfree** [comment]
This is actually the very first time I do smth with vault. So I'll probably have tons of questions, but i'll give my best. :+1:

**Comment by calvix** [comment]
Because of this https://github.com/giantswarm/giantswarm/issues/2070, in `hive` we use old SHA tag of cerctl so changes here wont affect it.

**Comment by xh3b4sd** [comment]
Well yeah, but the goal should be to use the latest, updated version, everywhere.

**Comment by indyfree** [comment]
Further note: `certctl` is also beeing used in 
- https://github.com/giantswarm/opsctl
- https://github.com/giantswarm/cluster-service
- https://github.com/giantswarm/giantnetes-terraform

**Comment by indyfree** [comment]
AIUI the cli `certctl` is broken, as reported in giantswarm/giantswarm#2070.

But packages as e.g. `certctlspec.CertSigner` or  `pki.Service` of certctl are vendored into these repos as libs. (We should maybe put them somewhere else instead)
- https://github.com/giantswarm/cluster-service
- https://github.com/giantswarm/opsctl

I vendored the packages of this branch into `cluster-service` and `opsctl` and successfully tested them. So on that side we should be good.

I would proceed with merging this PR and vendor it into the services to conclude the update vault story. Since the `certctl` tool itself is used in `hive` and `giantnetes-terraform`, but always referenced by an old SHA, i would see fixing and updating this stuff as part of another issue (giantswarm/giantswarm#2070) and tackle this seperatly. WDYT @xh3b4sd ?

**Comment by xh3b4sd** [comment]
> But packages as e.g. `certctlspec.CertSigner` or  `pki.Service` of certctl are vendored into these repos as libs. (We should maybe put them somewhere else instead)

So yeah this is the yak shave. All the  `certctlspec.CertSigner` or  `pki.Service` implementations are deprecated and only legacy. They should be replaced by the `vaultrole`, `vaultcrt`, `vaultpki` libs. There we started extracting all of the magic. `certctl` should not be imported anywhere anymore. I do not mind how you want to proceed. For me it is only important to fix https://github.com/giantswarm/giantswarm/issues/2070 and get the dep updates done so we have a good basis for the future finally again.

**Comment by indyfree** [comment]
The `certctl` part of https://github.com/giantswarm/giantswarm/issues/2070 has been addressed in #69 . This is now just vendoring. CI is green, so going with this.

**Pull request merged**
