### PR TITLE
Update to kubernetes-1.15.4

### PR DESCRIPTION
**Pull request by sslavic**
Towards https://github.com/giantswarm/giantswarm/issues/6302

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
LGTM

**Comment by rossf7** [comment]
@sslavic Looks like the e2e is outdated due to the k8sclients issue.

I think for deploying this we need to use a new tag in `hive` and maybe other places. @mazzy89 @corest Do you know what is needed?

**Comment by mazzy89** [comment]
Yeah correct you need to change theversion in hive as in here https://github.com/giantswarm/hive/pull/434

**Comment by sslavic** [comment]
Fixed build / e2e tests.

Merged PR. Created hive PR https://github.com/giantswarm/hive/pull/487 with updating certctl Docker image tag.

TODO apply changes / deploy new certctl to existing environments.

**Pull request merged**
